[build]
  cmd = "go run cmd/server/main.go"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "tmp", "node_modules"]
  exclude_file = ["*_test.go"]
  delay = 1000
  stop_on_error = true
  send_interrupt = true

[log]
  level = "info"
  time = true

[debug]
  enable = false
